// React entry for the hprof-analyzer HTML report.
//
// The uncompressed bootstrap (in the HTML shell) has already run: it inflated
// this bundle and injected it, and exposed:
//   - window.__HPROF_DATA_B64__  : base64 of raw-DEFLATE'd report JSON
//   - window.hprofDecodeText(b64): Promise<string> (inflate + UTF-8 decode)
// We decode + inflate + JSON.parse the report data, then render.
import React from "react";
import { createRoot } from "react-dom/client";
import App, { DiffApp, ErrorBoundary } from "./App";
import type { Report, SeriesDiffEnvelope } from "./types";
import css from "./styles.css";

function fail(msg: string): void {
  const root = document.getElementById("root");
  if (root) root.textContent = msg;
}

function injectStyles(): void {
  const style = document.createElement("style");
  style.textContent = css as unknown as string;
  document.head.appendChild(style);
}

async function boot(): Promise<void> {
  const b64 = window.__HPROF_DATA_B64__ || "";
  const decode = window.hprofDecodeText;
  if (!decode) {
    fail("Report bootstrap missing (hprofDecodeText).");
    return;
  }
  let parsed: Report | SeriesDiffEnvelope;
  try {
    const json = await decode(b64);
    parsed = JSON.parse(json) as Report | SeriesDiffEnvelope;
  } catch (e) {
    fail("Failed to parse report data: " + e);
    return;
  }
  injectStyles();
  const el = document.getElementById("root");
  if (!el) {
    fail("Missing #root element.");
    return;
  }
  // A single-dump Report has no `kind` field; the diff view wraps its payload
  // in a {"kind":"series-diff", diff} envelope so we can dispatch here.
  const isDiff =
    parsed != null &&
    typeof parsed === "object" &&
    (parsed as SeriesDiffEnvelope).kind === "series-diff";
  // Client-side schema version guard: refuse reports generated by a newer
  // hprof-analyzer than this viewer knows about (same policy as the Rust CLI).
  const CURRENT_SCHEMA_VERSION = 8;
  if (!isDiff) {
    const v = (parsed as Report).schema_version;
    if (typeof v === "number" && v > CURRENT_SCHEMA_VERSION) {
      fail(
        `This report was generated by a newer hprof-analyzer (schema version ${v}); ` +
        `this viewer supports up to version ${CURRENT_SCHEMA_VERSION}. ` +
        `Please upgrade the viewer.`
      );
      return;
    }
  }
  // Do NOT clear #root up front: createRoot().render replaces the container's
  // contents itself, and an early clear would leave a blank page if render threw
  // before painting. The ErrorBoundary catches render exceptions and shows a
  // panel; a synchronous mount failure falls through to fail() below.
  try {
    createRoot(el).render(
      <React.StrictMode>
        <ErrorBoundary>
          {isDiff ? (
            <DiffApp diff={(parsed as SeriesDiffEnvelope).diff} />
          ) : (
            <App report={parsed as Report} />
          )}
        </ErrorBoundary>
      </React.StrictMode>,
    );
  } catch (e) {
    fail("Failed to render report: " + e);
  }
}

void boot();
